build: off

platform:
  - x64

cache:
  - '%USERPROFILE%\.electron'
  - '%USERPROFILE%\.npm'

install:
  - ps: Install-Product node 10 x64
  - npm i

test_script:
  - node --version
  - npm --version
  - npm test-ie


